From jsmith@example.com  Thu Jan 01 12:16:37 2015
Return-Path: <jsmith@example.com>
From: John Doe <jsmith@example.com>
To: "'mlm-test@example.com'" <mlm-test@example.com>
Subject: test email
Thread-Topic: test email
Thread-Index: AczqKQkn80QG1mKsSAKtHhyneKP2LA==
Date: Thu, 01 Jan 2015 00:00:00 +0000
Message-ID: <537C03C37C4642E3B1E1E539A3F0944D@mx.example.com>
Accept-Language: ru-RU, en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
x-originating-ip: [10.0.0.2]
Content-Type: text/plain; charset="windows-1251"
Content-Transfer-Encoding: quoted-printable
MIME-Version: 1.0

This is a test email from MLMAdmin

